name: Build and Package

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Linux Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Build & Package
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Debug Linux build artifacts
        run: |
          echo "Workspace root:"
          ls -R .
          echo "dist directory:"
          ls -R dist

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-packages
          path: |
            dist/sitefocus_*.deb
            dist/sitefocus-*.rpm
            dist/sitefocus.desktop
            dist/sitefocus.appdata.xml
          if-no-files-found: ignore

  build-windows:
    name: Windows Package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller zip

      - name: Build & Package
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Debug Windows build artifacts
        run: |
          echo "Workspace root:"
          ls -R .
          echo "dist directory:"
          ls -R dist

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: |
            dist/sitefocus-*-windows.zip
          if-no-files-found: ignore

  build-macos:
    name: macOS Package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build & Package
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Debug macOS build artifacts
        run: |
          echo "Workspace root:"
          ls -R .
          echo "dist directory:"
          ls -R dist

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-package
          path: |
            dist/sitefocus-*-macos.zip
          if-no-files-found: ignore